wiki/config/routes.rb
Rails.application.routes.draw do
  get 'wiki_posts/example'
  resources :wiki_posts
  get 'welcome/index'
  get 'welcome/about'
  get 'about', to: redirect('/welcome/about')
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

wiki/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

wiki/app/models/wiki_post.rb
class WikiPost < ApplicationRecord
end

wiki/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

wiki/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = WikiPost.all
  end
  def about
  end
end

wiki/app/controllers/wiki_posts_controller.rb
class WikiPostsController < ApplicationController
  before_action :set_wiki_post, only: %i[ edit update destroy show ]

  # GET /wiki_posts or /wiki_posts.json
  def index
    @wiki_posts = WikiPost.all
  end

  # GET /wiki_posts/1 or /wiki_posts/1.json
  def show
  end

  def example
  end

  # GET /wiki_posts/new
  def new
    @wiki_post = WikiPost.new
  end

  # GET /wiki_posts/1/edit
  def edit
  end

  # POST /wiki_posts or /wiki_posts.json
  def create
    @wiki_post = WikiPost.new(wiki_post_params)

    respond_to do |format|
      if @wiki_post.save
        format.html { redirect_to wiki_post_url(@wiki_post), notice: "Wiki post was successfully created." }
        format.json { render :show, status: :created, location: @wiki_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wiki_posts/1 or /wiki_posts/1.json
  def update
    respond_to do |format|
      if @wiki_post.update(wiki_post_params)
        format.html { redirect_to wiki_post_url(@wiki_post), notice: "Wiki post was successfully updated." }
        format.json { render :show, status: :ok, location: @wiki_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wiki_posts/1 or /wiki_posts/1.json
  def destroy
    @wiki_post.destroy

    respond_to do |format|
      format.html { redirect_to wiki_posts_url, notice: "Wiki post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki_post
      @wiki_post = WikiPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wiki_post_params
      params.fetch(:wiki_post, {})
    end
end

wiki/app/helpers/application_helper.rb
module ApplicationHelper
end

wiki/app/helpers/welcome_helper.rb
module WelcomeHelper
end

wiki/app/helpers/wiki_posts_helper.rb
module WikiPostsHelper
end

wiki/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wiki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

wiki/app/views/welcome/about.html.erb
<h1>
    Wiki Information
</h1>

wiki/app/views/welcome/index.html.erb
<h1>Wiki</h1>

<p>Posts will go here</p>

<div>
    <% @posts.each do |post|%>
    <p>
        <h4><%= post.title %></h4>
        <%= link_to "View", wiki_post_path(post), class: 'wikiLink' %>
    </p>
    <% end %>
</div>

<%= link_to "About", welcome_about_path %>

wiki/app/views/wiki_posts/_form.html.erb
<%= form_with(model: wiki_post) do |form| %>
  <% if wiki_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wiki_post.errors.count, "error") %> prohibited this wiki_post from being saved:</h2>

      <ul>
        <% wiki_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

wiki/app/views/wiki_posts/edit.html.erb
<h1>Editing Wiki Post</h1>

<%= render 'form', wiki_post: @wiki_post %>

<%= link_to 'Show', @wiki_post %> |
<%= link_to 'Back', wiki_posts_path %>

wiki/app/views/wiki_posts/example.html.erb
<h1 class="title">Wiki Page Title</h1>

<p class="description">Wiki Page Body</p>

<div class="meta">
    <span class="author">Wiki Page Author</span>
    <span class="creation">Wiki Page Creation Date</span>
    <span class="update">Wiki Page Last Update Date</span>
</div>

<div class="links">
    <%= link_to 'Home', welcome_index_path %>
    <%= link_to 'New Wiki Post', new_wiki_post_path %>
</div>

wiki/app/views/wiki_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wiki Posts</h1>

<%= link_to 'New Wiki Post', new_wiki_post_path %>

wiki/app/views/wiki_posts/new.html.erb
<h1>New Wiki Post</h1>

<%= render 'form', wiki_post: @wiki_post %>

<%= link_to 'Back', wiki_posts_path %>

wiki/app/views/wiki_posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= @wiki_post.title %>

<%= link_to 'Edit', edit_wiki_post_path(@wiki_post) %> |
<%= link_to 'Back', wiki_posts_path %>